### ISSUE TITLE
IAM token expiration

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/clues-indigo#19]
The expiration of the IAM token causes the cluesserver failure in contacting the orchestrator.  A token refresh mechanism should be included to avoid that.

**Comment by micafer** [comment]
Merged to master.

**Comment by micafer** [comment]
@maricaantonacci It has been merged and tested. The only issue is that the token that you use to create the elastic cluster must have the scope "ofline_access" to enable the plugin to refresh the token. I will close this issue if you find any issue we will open a new one.
