### ISSUE TITLE
CPU and memory of mesos nodes are hardcoded when the nodes are off

### ISSUE THREAD

**Issue by micafer** [indigo-dc/clues-indigo#25]

**Comment by micafer** [comment]
https://github.com/indigo-dc/clues-indigo/blob/master/mesos.py#L308

**Comment by alpegon** [comment]
Two variables added to solve this issue:
 - MESOS_NODE_MEMORY
 - MESOS_NODE_SLOTS

You can set the value of this variables in the file: /etc/clues2/conf.d/plugin-mesos.cfg
