### ISSUE TITLE
Error in orchestrator plugin

### ISSUE THREAD

**Issue by micafer** [indigo-dc/clues-indigo#35]
As reported by @maricaantonacci clues log shows this error:

```
[PLUGIN-INDIGO-ORCHESTRATOR];DEBUG;2017-03-16 12:40:25,548;Deployment in status: UPDATE_COMPLETE
[PLUGIN-INDIGO-ORCHESTRATOR];DEBUG;2017-03-16 12:40:25,548;Processing pending tasks: [<cluesplugins.indigo_orchestrator.Task instance at 0x7f15edcf3cf8>].
[PLUGIN-INDIGO-ORCHESTRATOR];ERROR;2017-03-16 12:40:25,576;Error executing lifecycle of INDIGO Orchestrator PowerManager.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 564, in lifecycle
    self._process_pending_tasks(monitoring_info)
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 484, in _process_pending_tasks
    node_info = self._get_node_info(monitoring_info, task.nname)
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 452, in _get_node_info
    if node.nname == nname:
AttributeError: Node instance has no attribute 'nname'
```

**Comment by micafer** [comment]
Merged to master.
@maricaantonacci: Could you please test it?

**Comment by maricaantonacci** [comment]
Hi Miguel,
I have re-run the test with mesos and I can confirm that the notified error message is not issued any more...I get now another error:

[PLUGIN-INDIGO-ORCHESTRATOR];DEBUG;2017-03-21 16:05:01,406;Deployment in status: UPDATE_COMPLETE
[PLUGIN-INDIGO-ORCHESTRATOR];DEBUG;2017-03-21 16:05:01,406;Processing pending tasks: [<cluesplugins.indigo_orchestrator.Task instance at 0x7faaae126638>].
[PLUGIN-INDIGO-ORCHESTRATOR];WARNING;2017-03-21 16:05:02,369;Trying to poweroff node 64d48786-8453-4357-a0fa-91c18a0ed6f5 that is not in then monitoring info. Discard poweroff operation.
[PLUGIN-INDIGO-ORCHESTRATOR];ERROR;2017-03-21 16:05:02,369;Error executing lifecycle of INDIGO Orchestrator PowerManager.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 564, in lifecycle
    self._process_pending_tasks(monitoring_info)
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 495, in _process_pending_tasks
    task = self._pending_tasks[0]
IndexError: list index out of range

and

<pre>
# clues status
node                          state    enabled   time stable   (cpu,mem) used   (cpu,mem) total
-----------------------------------------------------------------------------------------------
vnode-1                    on (err)    enabled     15h04'19"    0.0,0.0          1.0,1048576000.0
vnode-2                    on (err)    enabled     14h50'49"    0.0,0.0          1.0,1048576000.0
vnode-3                    on (err)    enabled     15h16'49"    0.0,0.0          1.0,1048576000.0
vnode-4                        used    enabled     16h30'14"    0.2,402653184.0    1.0,1048576000.0
vnode-5                    on (err)    enabled     14h57'09"    0.0,0.0          1.0,1048576000.0

</pre>

**Comment by micafer** [comment]
Hi @maricaantonacci,

I fixed this error and merged to master.

**Comment by maricaantonacci** [comment]
Sorry, it does not work yet. 
The clues log reports several errors like:

[PLUGIN-MESOS]; INFO;2017-03-22 09:30:09,322;1490175009.322;Error resolving node ip vnode-1

[PLUGIN-INDIGO-ORCHESTRATOR];ERROR;2017-03-22 09:31:45,423;Error powering off nodes [] 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 729, in _power_off
    resp_status, output = self._modify_deployment(self._mvs_seen, remove_nodes=node_list)
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 665, in _modify_deployment
    template = self._get_template(len(vms), remove_nodes, add_nodes)
  File "/usr/local/lib/python2.7/dist-packages/cluesplugins/indigo_orchestrator.py", line 775, in _get_template
    node_template['capabilities']['scalable']['properties']['count'] = count + len(add_nodes)
TypeError: object of type 'NoneType' has no len()
[PLUGIN-INDIGO-ORCHESTRATOR];ERROR;2017-03-22 09:47:24,911;Error processing tasks: 

and 5 nodes have been instantiated

<pre>
clues status
node                          state    enabled   time stable   (cpu,mem) used   (cpu,mem) total
-----------------------------------------------------------------------------------------------
vnode-1                      powoff    enabled     00h02'27"    0.0,0.0          1.0,1048576000.0
vnode-2                      powoff    enabled     00h08'09"    0.0,0.0          1.0,1048576000.0
vnode-3                        idle    enabled     00h03'47"    0.0,0.0          1.0,1048576000.0
vnode-4                        used    enabled     00h46'07"    0.2,402653184.0    1.0,1048576000.0
vnode-5                        idle    enabled     00h00'37"    0.0,0.0          1.0,1048576000.0

</pre>

**Comment by micafer** [comment]
Hi @maricaantonacci,

I fixed this new error and merged to master.
But If you get another one, please send a email or skype and let me login in the cluster to debug properly the errors.
